# Generated by Django 4.2.27 on 2026-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_is_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_for_reset',
            field=models.BooleanField(default=False),
        ),
    ]
