# Generated by Django 4.2.27 on 2026-04-27 17:59

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.cover_upload_path),
        ),
    ]
