# Generated by Django 4.2.27 on 2026-04-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_avatar_version_customuser_cover_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_version',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cover_version',
        ),
    ]
